name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install libraries
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: install firebase
        run: npm i firebase-tools -g  
      - name: deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTHENTICATION_AB4CC }}

